service: <insert-service-name-here-no-space>

frameworkVersion: '3'

provider:
  name: azure
  region: West US 2
  runtime: nodejs14
  subscriptionId: <INSERT SUB ID HERE>
  stage: ${opt:stage, 'dev'} 
  environment:
    box_primary_key: "<INSERT PRIMARY KEY HERE>"
    box_secondary_key: "<INSERT SECONDARY KEY HERE>"
    box_api_endpoint: "https://api.box.com/2.0"

plugins:
  - serverless-azure-functions

package:
  patterns:
    - '!.gitignore'
    - '!.git/**'
    - '!local.settings.json'
    - '!.vscode/**'

functions:
  skill:
    handler: src/handlers/skill.boxSkill
    events:
      - http: true
        methods:
          - GET
          - POST
        authLevel: anonymous # can also be `function` or `admin`

