service: <insert-service-name-here-no-space>

provider:
  name: azure
  runtime: nodejs14.x
  timeout: 10 # server should still acknowledge Box skills engine within 10 seconds of receiving the event
  versionFunctions: true # maintains past versions in single deployment

