service: <insert-service-name-here-no-space>

provider:
    name: google
    stage: dev
    runtime: nodejs14
    region: us-central1
    project: <insert project id>
    credentials: <insert absolute file path>
    environment:
        box_primary_key: "<insert first key>"
        box_secondary_key: "<insert second key>"
        box_api_endpoint: "https://api.box.com/2.0"

plugins:
    - serverless-google-cloudfunctions

package:
    exclude:
        - node_modules/**
        - .gitignore
        - .git/**

functions:
    first:
        handler: boxSkill
        events:
            - http: path

