service: box-custom-skills-starter-gcp

provider:
    name: google
    stage: dev
    runtime: nodejs12
    region: us-central1
    project: <insert project id>
    credentials: <insert absolute file path>

plugins:
    - serverless-google-cloudfunctions

package:
    exclude:
        - node_modules/**
        - .gitignore
        - .git/**

functions:
    first:
        handler: boxSkill
        events:
            - http: path

