service: <insert-service-name-here-no-space>

# before you deploy your app, you should set credential with the follow cmd:
# serverless config credentials --provider aws --key $AWS_KEY$ --secret $AWS_SECRET$ -o
provider:
  name: aws
  runtime: nodejs14.x
  timeout: 10 # server should still acknowledge Box skills engine within 10 seconds of receiving the event
  versionFunctions: true # maintains past versions in single deployment
  environment:
    box_primary_key: "<INSERT PRIMARY KEY HERE>"
    box_secondary_key: "<INSERT SECONDARY KEY HERE>"
    box_api_endpoint: "https://api.box.com/2.0"

# overwriting defaults
  stage: ${opt:stage, 'dev'}
  region: us-west-2

# packaging information
package:
    exclude:
        - .gitignore
        - .git/**

functions:
  skill:
    handler: index.handler
    events: # The Events that trigger this Function
      - http:
          path: ${self:service}
          method: any
