# For full Serverless config options, check the docs:
#    https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/

service: my-quick-automated-demo

# You can change this to any cloud provider:
# AWS Lambda: <https://aws.amazon.com/lambda/>
# Microsoft Azure: <https://azure.microsoft.com/en-us/overview/serverless-computing/>
# Google Cloud Functions: <https://cloud.google.com/functions/>
# IBM Cloud Functions: <https://www.ibm.com/cloud/functions/details>
#
# before you deploy your app, you should set credential with the follow cmd:
# serverless config credentials --provider aws --key $AWS_KEY$ --secret $AWS_SECRET$ -o
provider:
  name: aws
  runtime: nodejs14.x
  timeout: 10 # server should still acknowledge Box skills engine within 10 seconds of receiving the event
  versionFunctions: true # maintains past versions in single deployment


# overwriting defaults
  stage: ${opt:stage, 'dev'}
  region: us-west-2

# packaging information
package:
    exclude:
        - .gitignore
        - .git/**
    excludeDevDependencies: false

functions:
  skill:
    handler: index.handler
    events: # The Events that trigger this Function
      - http:
          path: ${self:service}
          method: any
